version: '3.9'
services:
  user-service:
    build: ./microservices/user-service
    ports:
      - "8001:8001"
    depends_on:
      - mongodb

  waste-item-service:
    build: ./microservices/waste-item-service
    ports:
      - "8002:8002"
    depends_on:
      - mongodb

  waste-category-service:
    build: ./microservices/waste-category-service
    ports:
      - "8003:8003"
    depends_on:
      - mongodb

  challenge-service:
    build: ./microservices/challenge-service
    ports:
      - "8004:8004"
    depends_on:
      - mongodb


  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
      - ./db_confs/mongod.conf:/etc/mongo/mongod.conf
    command: [ "mongod", "--config", "/etc/mongo/mongod.conf" ]
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data:
